### ISSUE TITLE
Issue going back to the homepage

### ISSUE THREAD

**Issue by sdras** [sdras/contentful-nuxt-netlify#1]
Not present on the repo this was forked from

Reported from twitter:
https://twitter.com/KovskyD/status/1252277673956708354?s=20

**Comment by debs-obrien** [comment]
Hi @sdras Just to let you know that issue of returning to the home page is still there. We are featuring it tomorrow in the NuxtJS newsletter so just thought I would give you the heads up incase you have time to look into :)

**Comment by sdras** [comment]
All fixed! As mentioned in the post, it's forked from my stepdaughter's blog and she posted to the fork and it broke the author fields. Should be all good now.

**Comment by debs-obrien** [comment]
Thanks @sdras. You are best. Love your work as always 😘
