### ISSUE TITLE
Link to instructions in README returns 404

### ISSUE THREAD

**Issue by bigsee** [sdras/contentful-nuxt-netlify#2]
Thank you for providing this example - look forward to trying out creating a blog using this stack!

Unfortunately the link in the README returns 404:

![Screen Shot 2020-04-22 at 13 12 17](https://user-images.githubusercontent.com/11768967/79975356-21cb7280-849b-11ea-8e4c-1026286277d2.png)

...and there doesn't seem to be a saved version:

![Screen Shot 2020-04-22 at 13 12 36](https://user-images.githubusercontent.com/11768967/79975361-24c66300-849b-11ea-8e81-8ef0841e8068.png)

**Comment by bigsee** [comment]
I notice that the link in the README omits the `www` from the link. I managed to find the blog post on the Netlify site and that's the only difference I notice. When I navigate directly to [https://www.netlify.com/blog/2020/04/20/create-a-blog-with-contentful-and-nuxt/](https://www.netlify.com/blog/2020/04/20/create-a-blog-with-contentful-and-nuxt/) it seems to work. Maybe a redirect issue?

Couldn't clone and update as I need a Contentful access token. Sorry!

**Comment by sdras** [comment]
Someone updated the date of the post and it updated the url :) should be all good!
